import { useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { Loading, LoadingPage } from "~/components/loading";

const ProfilePage: NextPage = () => { 

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        Profile View
      </main>
    </>
  );
};

export default ProfilePage;
