import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import { RouterOptions } from "next/dist/server/router";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import { api } from "~/utils/api";

const CreatePostWizzard = () => {

  const { user } = useUser();

  // TODO: Add some error handling here
  if ( !user ) return null;

  return (
  <div className="flex gap-4 w-full">
    <Image src={user.profileImageUrl} alt="Profile Image" className="w-16 h-16 rounded-full" width={56} height={56}/>
    <input placeholder="Type something bitte" className="bg-transparent grow outline-none" />
  </div>
  );

};

type PostWithUser = RouterOptions['post']['getAll'][number];
const PostView = (props: PostWithUser) => {
  const { post, author } = props;
  return (
    <div key={post.id} className="border-b border-slate-400 p-4 flex gap-3">
      <Image src={author.profileImageUrl} alt="Author Profile Picture" className="w-16 h-16 rounded-full" width={56} height={56}/>
      <div className="flex flex-col">
        <div className="flex">
          <span>{`@${author.username}`}</span>
        </div>
        <span>{post.content}</span>  
      </div>
    </div>
  );
};

const Home: NextPage = () => { 

  const user = useUser();
  const { data, isLoading } = api.posts.getAll.useQuery();

  if ( isLoading ) return <div>Loading...</div>;

  if ( !data ) return <div>Something went wrong...</div>;

  console.log(user);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className="w-full md:max-w-2xl border-x border-slate-400">
          <div className="flex border-b border-slate-400 p-4 ">
            {!user.isSignedIn && (
            <div className="justify-center flex">
              <SignInButton />
              </div>
            )} 
            {!!user.isSignedIn && (
            <CreatePostWizzard />
            // <div className="justify-center flex">
            //   <SignOutButton />
            // </div>
            )}
          </div>
          <div className="flex flex-col">
            {[...data, ...data]?.map((fullPost) => (
              <PostView {...fullPost} key={fullPost.post.id} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
